apiVersion: v1
kind: Service
metadata:
  name: stolon-proxy-service
spec:
  selector:
    component: stolon-proxy
    stolon-cluster: kube-stolon
  type: NodePort
  ports:
  - port: 5432
    name: n5432
    targetPort: 5432
    nodePort: 35432
  - port: 8080
    targetPort: 8080
    nodePort: 38080
    name: n8080

